//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace orderline.core.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("orderline.core.Resources.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! This order being before order number {0}.
        /// </summary>
        public static string ActivateDocAttention {
            get {
                return ResourceManager.GetString("ActivateDocAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Code.
        /// </summary>
        public static string ActivationCode {
            get {
                return ResourceManager.GetString("ActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setress.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setress Information.
        /// </summary>
        public static string AddressInfo {
            get {
                return ResourceManager.GetString("AddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setressnumber.
        /// </summary>
        public static string Addressnumber {
            get {
                return ResourceManager.GetString("Addressnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of searching addresses.
        /// </summary>
        public static string AddressSearchType {
            get {
                return ResourceManager.GetString("AddressSearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetresNr.
        /// </summary>
        public static string Adressnumber {
            get {
                return ResourceManager.GetString("Adressnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        public static string ago {
            get {
                return ResourceManager.GetString("ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocketseller.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article already exists, do you want add this?.
        /// </summary>
        public static string ArticleAlreadyExists {
            get {
                return ResourceManager.GetString("ArticleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Deficits.
        /// </summary>
        public static string ArticleDeficits {
            get {
                return ResourceManager.GetString("ArticleDeficits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArticleNr.
        /// </summary>
        public static string Articlenumber {
            get {
                return ResourceManager.GetString("Articlenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of searching articles.
        /// </summary>
        public static string ArticleSearchType {
            get {
                return ResourceManager.GetString("ArticleSearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really want delete this?.
        /// </summary>
        public static string AskDeleteOrder {
            get {
                return ResourceManager.GetString("AskDeleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really want delete this?.
        /// </summary>
        public static string AskForDeleteDB {
            get {
                return ResourceManager.GetString("AskForDeleteDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really want delete this?.
        /// </summary>
        public static string AskForDeleteDoc {
            get {
                return ResourceManager.GetString("AskForDeleteDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really???.
        /// </summary>
        public static string AskIfReally {
            get {
                return ResourceManager.GetString("AskIfReally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases are sucessfully saved.
        /// </summary>
        public static string BackupCompleted {
            get {
                return ResourceManager.GetString("BackupCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Database.
        /// </summary>
        public static string BackupDatabase {
            get {
                return ResourceManager.GetString("BackupDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning of word.
        /// </summary>
        public static string BeginningOfWord {
            get {
                return ResourceManager.GetString("BeginningOfWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Menu.
        /// </summary>
        public static string CanceledOptionMenu {
            get {
                return ResourceManager.GetString("CanceledOptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        public static string Changed {
            get {
                return ResourceManager.GetString("Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges.
        /// </summary>
        public static string Charges {
            get {
                return ResourceManager.GetString("Charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check EK.
        /// </summary>
        public static string CheckEK {
            get {
                return ResourceManager.GetString("CheckEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque No.
        /// </summary>
        public static string CheckqueNr {
            get {
                return ResourceManager.GetString("CheckqueNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check stock.
        /// </summary>
        public static string CheckStock {
            get {
                return ResourceManager.GetString("CheckStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comission.
        /// </summary>
        public static string Comission {
            get {
                return ResourceManager.GetString("Comission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string CorrectFactura {
            get {
                return ResourceManager.GetString("CorrectFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources could not be downloaded, maybe that your device is not registrated..
        /// </summary>
        public static string CouldNotBeActivated {
            get {
                return ResourceManager.GetString("CouldNotBeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeStamp.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new one.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Order.
        /// </summary>
        public static string CreateOrder {
            get {
                return ResourceManager.GetString("CreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        public static string CurrentStockAmount {
            get {
                return ResourceManager.GetString("CurrentStockAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOLI.
        /// </summary>
        public static string CurrentStockCount {
            get {
                return ResourceManager.GetString("CurrentStockCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbName Archive.
        /// </summary>
        public static string DatabaseArchive {
            get {
                return ResourceManager.GetString("DatabaseArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbName Check.
        /// </summary>
        public static string DatabaseCheck {
            get {
                return ResourceManager.GetString("DatabaseCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbName.
        /// </summary>
        public static string DatabaseSettings {
            get {
                return ResourceManager.GetString("DatabaseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data flow.
        /// </summary>
        public static string Dataflow {
            get {
                return ResourceManager.GetString("Dataflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datatransfer.
        /// </summary>
        public static string Datatransfer {
            get {
                return ResourceManager.GetString("Datatransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string DateStart {
            get {
                return ResourceManager.GetString("DateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string DateStop {
            get {
                return ResourceManager.GetString("DateStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        public static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Menu.
        /// </summary>
        public static string DeficitOptionMenu {
            get {
                return ResourceManager.GetString("DeficitOptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deficits.
        /// </summary>
        public static string Deficits {
            get {
                return ResourceManager.GetString("Deficits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete DbName.
        /// </summary>
        public static string DeleteDatabase {
            get {
                return ResourceManager.GetString("DeleteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Menu.
        /// </summary>
        public static string DeletedOptionMenu {
            get {
                return ResourceManager.GetString("DeletedOptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Menu.
        /// </summary>
        public static string DeleteOptionMenu {
            get {
                return ResourceManager.GetString("DeleteOptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard and Stay.
        /// </summary>
        public static string DiscardAndStay {
            get {
                return ResourceManager.GetString("DiscardAndStay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position details.
        /// </summary>
        public static string Documentdetail {
            get {
                return ResourceManager.GetString("Documentdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Menu.
        /// </summary>
        public static string DocumentdetailsOptionMenu {
            get {
                return ResourceManager.GetString("DocumentdetailsOptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Menu.
        /// </summary>
        public static string DocumentsOptionMenu {
            get {
                return ResourceManager.GetString("DocumentsOptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want backup your databases?.
        /// </summary>
        public static string DoYouWantBackupDatabase {
            get {
                return ResourceManager.GetString("DoYouWantBackupDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want delete this order?.
        /// </summary>
        public static string DoYouWantDelete {
            get {
                return ResourceManager.GetString("DoYouWantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want import this order?.
        /// </summary>
        public static string DoYouWantImport {
            get {
                return ResourceManager.GetString("DoYouWantImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want restore your databases?.
        /// </summary>
        public static string DoYouWantRestoreDatabase {
            get {
                return ResourceManager.GetString("DoYouWantRestoreDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want update your Excel templates?.
        /// </summary>
        public static string DoYouWantUpdateTemplates {
            get {
                return ResourceManager.GetString("DoYouWantUpdateTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Comission.
        /// </summary>
        public static string EditComission {
            get {
                return ResourceManager.GetString("EditComission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Export.
        /// </summary>
        public static string ErpExport {
            get {
                return ResourceManager.GetString("ErpExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want exit?.
        /// </summary>
        public static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you want exit this document?.
        /// </summary>
        public static string ExitMessageHow {
            get {
                return ResourceManager.GetString("ExitMessageHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit this modul?.
        /// </summary>
        public static string ExitModul {
            get {
                return ResourceManager.GetString("ExitModul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want exit Pocketseller?.
        /// </summary>
        public static string ExitProgram {
            get {
                return ResourceManager.GetString("ExitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit without Save.
        /// </summary>
        public static string ExitWithoutSave {
            get {
                return ResourceManager.GetString("ExitWithoutSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string FacturaAll {
            get {
                return ResourceManager.GetString("FacturaAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Day.
        /// </summary>
        public static string FacturaDays {
            get {
                return ResourceManager.GetString("FacturaDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defects.
        /// </summary>
        public static string FacturaDefect {
            get {
                return ResourceManager.GetString("FacturaDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto.
        /// </summary>
        public static string FacturaKonto {
            get {
                return ResourceManager.GetString("FacturaKonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Week.
        /// </summary>
        public static string FacturaWeek {
            get {
                return ResourceManager.GetString("FacturaWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from now.
        /// </summary>
        public static string fromnow {
            get {
                return ResourceManager.GetString("fromnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VK &gt; EK + %.
        /// </summary>
        public static string GreaterEKInPercent {
            get {
                return ResourceManager.GetString("GreaterEKInPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Menu.
        /// </summary>
        public static string ImportOptionMenu {
            get {
                return ResourceManager.GetString("ImportOptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your DbName is deleted.
        /// </summary>
        public static string InfoDatabaseDeleted {
            get {
                return ResourceManager.GetString("InfoDatabaseDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be &gt;= than the purchase, do you want still take?.
        /// </summary>
        public static string InfoPriceMustGreaterThanEK {
            get {
                return ResourceManager.GetString("InfoPriceMustGreaterThanEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is to high, please check price.
        /// </summary>
        public static string InfoPriceMustInRange {
            get {
                return ResourceManager.GetString("InfoPriceMustInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock to low, do you want still take?.
        /// </summary>
        public static string InfoStockNotAvailable {
            get {
                return ResourceManager.GetString("InfoStockNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.Date.
        /// </summary>
        public static string InvoiceDate1 {
            get {
                return ResourceManager.GetString("InvoiceDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        public static string InvoiceNr {
            get {
                return ResourceManager.GetString("InvoiceNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Nr.
        /// </summary>
        public static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Open.
        /// </summary>
        public static string InvoiceOpen {
            get {
                return ResourceManager.GetString("InvoiceOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Duration.
        /// </summary>
        public static string InvoiceValue {
            get {
                return ResourceManager.GetString("InvoiceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocketseller is activated.
        /// </summary>
        public static string IsActivated {
            get {
                return ResourceManager.GetString("IsActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocketseller could not be activated.
        /// </summary>
        public static string IsNotActivated {
            get {
                return ResourceManager.GetString("IsNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybard in Documentdetail.
        /// </summary>
        public static string KeyboardInDocumentdetail {
            get {
                return ResourceManager.GetString("KeyboardInDocumentdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybard on search.
        /// </summary>
        public static string KeyboardOnSearch {
            get {
                return ResourceManager.GetString("KeyboardOnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Payment Craft [Day].
        /// </summary>
        public static string LabelAveragePaymentCraftInDays {
            get {
                return ResourceManager.GetString("LabelAveragePaymentCraftInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string LabelReady {
            get {
                return ResourceManager.GetString("LabelReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Langage {
            get {
                return ResourceManager.GetString("Langage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC.
        /// </summary>
        public static string LastCount {
            get {
                return ResourceManager.GetString("LastCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LD.
        /// </summary>
        public static string LastDate {
            get {
                return ResourceManager.GetString("LastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Import.
        /// </summary>
        public static string LastImport {
            get {
                return ResourceManager.GetString("LastImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LP.
        /// </summary>
        public static string LastPrice {
            get {
                return ResourceManager.GetString("LastPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successfull.
        /// </summary>
        public static string LoginSuccessFull {
            get {
                return ResourceManager.GetString("LoginSuccessFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic LowerCase.
        /// </summary>
        public static string LowerCaseSearchType {
            get {
                return ResourceManager.GetString("LowerCaseSearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input &lt; EK + %.
        /// </summary>
        public static string LowerInputInPercent {
            get {
                return ResourceManager.GetString("LowerInputInPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMails could not received.
        /// </summary>
        public static string MailsNotReceived {
            get {
                return ResourceManager.GetString("MailsNotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal Positions in Order.
        /// </summary>
        public static string MaxDocumentDetails {
            get {
                return ResourceManager.GetString("MaxDocumentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Position in Document achieved.
        /// </summary>
        public static string MaxDocumentDetailsAchieved {
            get {
                return ResourceManager.GetString("MaxDocumentDetailsAchieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name1.
        /// </summary>
        public static string Name1 {
            get {
                return ResourceManager.GetString("Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name2.
        /// </summary>
        public static string Name2 {
            get {
                return ResourceManager.GetString("Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order.
        /// </summary>
        public static string NewOrder {
            get {
                return ResourceManager.GetString("NewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Orders.
        /// </summary>
        public static string NewOrders {
            get {
                return ResourceManager.GetString("NewOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword1 {
            get {
                return ResourceManager.GetString("NewPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Type New Password.
        /// </summary>
        public static string NewPassword2 {
            get {
                return ResourceManager.GetString("NewPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Quotations.
        /// </summary>
        public static string NewQuotations {
            get {
                return ResourceManager.GetString("NewQuotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device does not have network access, please check and try again.
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Result.
        /// </summary>
        public static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string NormalKeyboard {
            get {
                return ResourceManager.GetString("NormalKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string NormalSearchType {
            get {
                return ResourceManager.GetString("NormalSearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Not Activated**.
        /// </summary>
        public static string NotActivated {
            get {
                return ResourceManager.GetString("NotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is not registered.
        /// </summary>
        public static string NotRegistered {
            get {
                return ResourceManager.GetString("NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit Keyboard.
        /// </summary>
        public static string NumberKeyboard {
            get {
                return ResourceManager.GetString("NumberKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OP.
        /// </summary>
        public static string OP {
            get {
                return ResourceManager.GetString("OP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OP Manager.
        /// </summary>
        public static string OpManager {
            get {
                return ResourceManager.GetString("OpManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order could not be sent, please try again..
        /// </summary>
        public static string OrderCouldNotBeSent {
            get {
                return ResourceManager.GetString("OrderCouldNotBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Deficits.
        /// </summary>
        public static string OrderDeficits {
            get {
                return ResourceManager.GetString("OrderDeficits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information for this Order.
        /// </summary>
        public static string OrderInfo {
            get {
                return ResourceManager.GetString("OrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest Bill is not payed within 45 days. No further order can be accepted. Please go in contact with our Accounting..
        /// </summary>
        public static string OrderNotSavable {
            get {
                return ResourceManager.GetString("OrderNotSavable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not saved.
        /// </summary>
        public static string OrderNotSaved {
            get {
                return ResourceManager.GetString("OrderNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordernumber start.
        /// </summary>
        public static string OrderNumberBegin {
            get {
                return ResourceManager.GetString("OrderNumberBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordernumber current.
        /// </summary>
        public static string OrderNumberCurrent {
            get {
                return ResourceManager.GetString("OrderNumberCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order saved.
        /// </summary>
        public static string OrderSaved {
            get {
                return ResourceManager.GetString("OrderSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search after x Char.
        /// </summary>
        public static string OrderSearchMaxChar {
            get {
                return ResourceManager.GetString("OrderSearchMaxChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order was sent successfully.
        /// </summary>
        public static string OrderSentSuccessfully {
            get {
                return ResourceManager.GetString("OrderSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V. Netto.
        /// </summary>
        public static string OrderValue {
            get {
                return ResourceManager.GetString("OrderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V. Brutto.
        /// </summary>
        public static string OrderValueVat {
            get {
                return ResourceManager.GetString("OrderValueVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall in word.
        /// </summary>
        public static string OverallInWord {
            get {
                return ResourceManager.GetString("OverallInWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcel.
        /// </summary>
        public static string Parcel {
            get {
                return ResourceManager.GetString("Parcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalParcels.
        /// </summary>
        public static string Parcels {
            get {
                return ResourceManager.GetString("Parcels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Quotations.
        /// </summary>
        public static string PastQuotations {
            get {
                return ResourceManager.GetString("PastQuotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed.
        /// </summary>
        public static string Payed {
            get {
                return ResourceManager.GetString("Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.Date.
        /// </summary>
        public static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.Text.
        /// </summary>
        public static string PaymentText {
            get {
                return ResourceManager.GetString("PaymentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalnumber.
        /// </summary>
        public static string PersonalId {
            get {
                return ResourceManager.GetString("PersonalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone1.
        /// </summary>
        public static string Phone1 {
            get {
                return ResourceManager.GetString("Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone2.
        /// </summary>
        public static string Phone2 {
            get {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Keyboard.
        /// </summary>
        public static string PhoneKeyboard {
            get {
                return ResourceManager.GetString("PhoneKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url for Pictures.
        /// </summary>
        public static string PictureUrl {
            get {
                return ResourceManager.GetString("PictureUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos.
        /// </summary>
        public static string Pos {
            get {
                return ResourceManager.GetString("Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string PositionTotal {
            get {
                return ResourceManager.GetString("PositionTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autom. Price Selecting.
        /// </summary>
        public static string PriceSelect {
            get {
                return ResourceManager.GetString("PriceSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Cash.
        /// </summary>
        public static string PrintCash {
            get {
                return ResourceManager.GetString("PrintCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comission Print.
        /// </summary>
        public static string PrintComission {
            get {
                return ResourceManager.GetString("PrintComission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Deliverynote Without Price.
        /// </summary>
        public static string PrintDeliveryNoteWithoutPrice {
            get {
                return ResourceManager.GetString("PrintDeliveryNoteWithoutPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Deliverynote With Price.
        /// </summary>
        public static string PrintDeliveryNoteWithPrice {
            get {
                return ResourceManager.GetString("PrintDeliveryNoteWithPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Menu.
        /// </summary>
        public static string PrintedOptionMenu {
            get {
                return ResourceManager.GetString("PrintedOptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Factura.
        /// </summary>
        public static string PrintFactura {
            get {
                return ResourceManager.GetString("PrintFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Menu.
        /// </summary>
        public static string PrintOptionMenu {
            get {
                return ResourceManager.GetString("PrintOptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put it back.
        /// </summary>
        public static string PutBack {
            get {
                return ResourceManager.GetString("PutBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Quotation.
        /// </summary>
        public static string Quotation {
            get {
                return ResourceManager.GetString("Quotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation could not be sent, please try again..
        /// </summary>
        public static string QuotationCouldNotBeSent {
            get {
                return ResourceManager.GetString("QuotationCouldNotBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation not saved.
        /// </summary>
        public static string QuotationNotSaved {
            get {
                return ResourceManager.GetString("QuotationNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Quotations.
        /// </summary>
        public static string Quotations {
            get {
                return ResourceManager.GetString("Quotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation saved.
        /// </summary>
        public static string QuotationSaved {
            get {
                return ResourceManager.GetString("QuotationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select From Special Offers.
        /// </summary>
        public static string QuotationSelector {
            get {
                return ResourceManager.GetString("QuotationSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation was sent successfully.
        /// </summary>
        public static string QuotationSentSuccessfully {
            get {
                return ResourceManager.GetString("QuotationSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation No.
        /// </summary>
        public static string QuotationsNr {
            get {
                return ResourceManager.GetString("QuotationsNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Menu.
        /// </summary>
        public static string QutotationsNewOptionMenu {
            get {
                return ResourceManager.GetString("QutotationsNewOptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Menu.
        /// </summary>
        public static string QutotationsSentOptionMenu {
            get {
                return ResourceManager.GetString("QutotationsSentOptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Menu.
        /// </summary>
        public static string QutotationValidOptionMenu {
            get {
                return ResourceManager.GetString("QutotationValidOptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reacreate table.
        /// </summary>
        public static string RecreateTable {
            get {
                return ResourceManager.GetString("RecreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew Account Data.
        /// </summary>
        public static string RenewAccountData {
            get {
                return ResourceManager.GetString("RenewAccountData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew Setress Data.
        /// </summary>
        public static string RenewAddressData {
            get {
                return ResourceManager.GetString("RenewAddressData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string RenewAll {
            get {
                return ResourceManager.GetString("RenewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew Article Data.
        /// </summary>
        public static string RenewArticleData {
            get {
                return ResourceManager.GetString("RenewArticleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew Outstanding Payments.
        /// </summary>
        public static string RenewOutstandingpayments {
            get {
                return ResourceManager.GetString("RenewOutstandingpayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases are sucessfully restored.
        /// </summary>
        public static string RestoreCompleted {
            get {
                return ResourceManager.GetString("RestoreCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Database.
        /// </summary>
        public static string RestoreDatabase {
            get {
                return ResourceManager.GetString("RestoreDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right now.
        /// </summary>
        public static string rightnow {
            get {
                return ResourceManager.GetString("rightnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Exit.
        /// </summary>
        public static string SaveAndExit {
            get {
                return ResourceManager.GetString("SaveAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Send.
        /// </summary>
        public static string SaveAndSend {
            get {
                return ResourceManager.GetString("SaveAndSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this order?.
        /// </summary>
        public static string SaveOrder {
            get {
                return ResourceManager.GetString("SaveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Setress.
        /// </summary>
        public static string SearchAddress {
            get {
                return ResourceManager.GetString("SearchAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Article.
        /// </summary>
        public static string SearchArticle {
            get {
                return ResourceManager.GetString("SearchArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching type.
        /// </summary>
        public static string SearchType {
            get {
                return ResourceManager.GetString("SearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase price.
        /// </summary>
        public static string SelectEKPrice {
            get {
                return ResourceManager.GetString("SelectEKPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send as Creditnote.
        /// </summary>
        public static string SendAsCreditNote {
            get {
                return ResourceManager.GetString("SendAsCreditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send as Deliverynote.
        /// </summary>
        public static string SendAsDelivery {
            get {
                return ResourceManager.GetString("SendAsDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send as Factura.
        /// </summary>
        public static string SendAsFactura {
            get {
                return ResourceManager.GetString("SendAsFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send as Order.
        /// </summary>
        public static string SendAsOrder {
            get {
                return ResourceManager.GetString("SendAsOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Orders.
        /// </summary>
        public static string SendOrders {
            get {
                return ResourceManager.GetString("SendOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Orders.
        /// </summary>
        public static string SentOrders {
            get {
                return ResourceManager.GetString("SentOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Quotations.
        /// </summary>
        public static string SentQuotations {
            get {
                return ResourceManager.GetString("SentQuotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set date greater or equal of start date.
        /// </summary>
        public static string SetDateGreaterEqualStart {
            get {
                return ResourceManager.GetString("SetDateGreaterEqualStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set date less or equal of end date.
        /// </summary>
        public static string SetDateLessEqualStop {
            get {
                return ResourceManager.GetString("SetDateLessEqualStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source detail.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB File.
        /// </summary>
        public static string SourceDatabase {
            get {
                return ResourceManager.GetString("SourceDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string SourceHost {
            get {
                return ResourceManager.GetString("SourceHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Menu.
        /// </summary>
        public static string SourceOptionMenu {
            get {
                return ResourceManager.GetString("SourceOptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of order could not be changed.
        /// </summary>
        public static string StatusNotChanged {
            get {
                return ResourceManager.GetString("StatusNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay.
        /// </summary>
        public static string Stay {
            get {
                return ResourceManager.GetString("Stay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Storno {
            get {
                return ResourceManager.GetString("Storno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string TabAccount {
            get {
                return ResourceManager.GetString("TabAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string TabAddress {
            get {
                return ResourceManager.GetString("TabAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string TabInfo {
            get {
                return ResourceManager.GetString("TabInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration [s].
        /// </summary>
        public static string TableImportDuration {
            get {
                return ResourceManager.GetString("TableImportDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        public static string TableImportLastUpdate {
            get {
                return ResourceManager.GetString("TableImportLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row count.
        /// </summary>
        public static string TableItemCount {
            get {
                return ResourceManager.GetString("TableItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        public static string TableItemName {
            get {
                return ResourceManager.GetString("TableItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outstanding.
        /// </summary>
        public static string TabOustanding {
            get {
                return ResourceManager.GetString("TabOustanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos.
        /// </summary>
        public static string TabPositions {
            get {
                return ResourceManager.GetString("TabPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Over.
        /// </summary>
        public static string TakeOver {
            get {
                return ResourceManager.GetString("TakeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string ToCanceled {
            get {
                return ResourceManager.GetString("ToCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditnote.
        /// </summary>
        public static string ToCreditNote {
            get {
                return ResourceManager.GetString("ToCreditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deficit.
        /// </summary>
        public static string ToDeficit {
            get {
                return ResourceManager.GetString("ToDeficit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ToDelete {
            get {
                return ResourceManager.GetString("ToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string ToDeleted {
            get {
                return ResourceManager.GetString("ToDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string ToDelivery {
            get {
                return ResourceManager.GetString("ToDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura.
        /// </summary>
        public static string ToFactura {
            get {
                return ResourceManager.GetString("ToFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string ToPrint {
            get {
                return ResourceManager.GetString("ToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed.
        /// </summary>
        public static string ToPrinted {
            get {
                return ResourceManager.GetString("ToPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Open.
        /// </summary>
        public static string TotalOpen {
            get {
                return ResourceManager.GetString("TotalOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Excel Templates.
        /// </summary>
        public static string UpdateExcelTemplate {
            get {
                return ResourceManager.GetString("UpdateExcelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update templates successfully completed.
        /// </summary>
        public static string UpdateTemplatesCompleted {
            get {
                return ResourceManager.GetString("UpdateTemplatesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic UpperCase.
        /// </summary>
        public static string UpperCaseSearchType {
            get {
                return ResourceManager.GetString("UpperCaseSearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        public static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Quotations.
        /// </summary>
        public static string ValidQuotations {
            get {
                return ResourceManager.GetString("ValidQuotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
